#!/usr/bin/env python3
"""House web tokens: the approved presets, checked with the grid equation, and
written out as CSS (assets/house-web.css) or printed as a table.

  tokens.py table        print every preset with its proof line
  tokens.py css > out    write the CSS tokens and utilities

Every px value is a 5 px step. CSS is emitted in rem (1rem = 16 px).
"""
import sys

STEP, COLS, ROOT = 5, 12, 16
CAP_RATIO = 0.7285  # Lato Black cap height / em (measured in InDesign, Adobe Fonts)

# Stepped containers: (container, {preset: (margin, module, gutter)})
# Rows are 1:1 ratio modules, so row = module.
CONTAINERS = {
    1200: {"a": (65, 80, 10), "b": (70, 70, 20), "c": (75, 60, 30), "d": (80, 50, 40)},
    1020: {"a": (35, 70, 10), "b": (40, 60, 20), "c": (45, 50, 30), "d": (50, 40, 40)},
    760:  {"a": (25, 50, 10), "b": (30, 40, 20), "c": (35, 30, 30), "d": (35, 30, 30)},  # D capped to C
    360:  {p: (35, 15, 10) for p in "abcd"},  # every preset collapses on mobile
}

# Heading cap heights (px) per container. size = cap / CAP_RATIO; leading = 1.5 x cap, up to 5.
HEADINGS = {
    "title": {1200: 60, 1020: 60, 760: 50, 360: 30},
    "h1":    {1200: 40, 1020: 40, 760: 30, 360: 25},
    "h2":    {1200: 30, 1020: 30, 760: 25, 360: 20},
    "h3":    {1200: 20, 1020: 20, 760: 20, 360: 15},
    "h4":    {1200: 15, 1020: 15, 760: 15, 360: 15},
}
BODY = {"body": (18, 25), "small": (16, 25), "condensed": (18, 20), "h5": (18, 25)}

GREYS = {k: h for k, h in zip(range(0, 101, 10), [
    "#FFFFFF", "#E6E6E6", "#CCCCCC", "#B3B3B3", "#999999", "#808080",
    "#666666", "#4D4D4D", "#333333", "#1A1A1A", "#000000"])}
DOMAINS = {  # slug (as in house-tokens.md): (H accent, S shade, T tint, text on H)
    "critical-thinking":                                ("#FF585D", "#551C25", "#F5DADF", "#000000"),
    "creative-thinking-problem-solving-and-innovation": ("#F19C49", "#4F2C1D", "#FFDFB4", "#000000"),
    "communication":                                    ("#F3EA5D", "#CFB500", "#F7F4A2", "#000000"),
    "self-management-and-organisation":                 ("#C5E86C", "#1C4220", "#EFF4A4", "#000000"),
    "responsibility-and-stewardship":                   ("#00B2A2", "#024638", "#D7EFE7", "#000000"),
    "practical-skills-and-technical-application":       ("#326295", "#041E42", "#D5EBEE", "#FFFFFF"),
    "knowledge-and-conceptual-understanding":           ("#514689", "#201547", "#DCD3E7", "#FFFFFF"),
    "independent-learning-and-collaboration":           ("#E56DB1", "#621244", "#F2DEE9", "#000000"),
}
LARGE_ONLY = {"critical-thinking", "practical-skills-and-technical-application"}  # H fill 6.8 / 6.3:1


def rem(px):
    return f"{px / ROOT:g}rem" if px else "0"


def leading(cap):
    return -(-cap * 3 // 2 // STEP) * STEP if (cap * 3) % (2 * STEP) else cap * 3 // 2


def check():
    for width, presets in CONTAINERS.items():
        for p, (m, mod, g) in presets.items():
            assert 2 * m + COLS * mod + (COLS - 1) * g == width, (width, p)
            assert all(v % STEP == 0 for v in (m, mod, g)), (width, p)
    for level, caps in HEADINGS.items():
        for w, cap in caps.items():
            assert cap % STEP == 0 and leading(cap) % STEP == 0, (level, w)


def table():
    for width, presets in CONTAINERS.items():
        print(f"== container {width}")
        for p, (m, mod, g) in presets.items():
            print(f"  {p.upper()}: module {mod}, gutter {g}, margin {m}, row {mod}, "
                  f"pitch {mod + g}   {m} + 12 × {mod} + 11 × {g} + {m} = {width}")
    print("== headings (cap → size / leading px)")
    for level, caps in HEADINGS.items():
        print(f"  {level:5} " + "  ".join(
            f"{w}: {c} → {c / CAP_RATIO:.1f} / {leading(c)}" for w, c in caps.items()))


def vars_for(width, preset):
    m, mod, g = CONTAINERS[width][preset]
    return (f"--hw-container: {rem(width)}; --hw-margin: {rem(m)}; "
            f"--hw-module: {rem(mod)}; --hw-gutter: {rem(g)}; --hw-row: {rem(mod)}; "
            f"--hw-pitch: {rem(mod + g)};")


def heading_vars(width):
    out = []
    for level, caps in HEADINGS.items():
        cap = caps[width]
        out.append(f"--hw-{level}-size: {round(cap / CAP_RATIO, 1) / ROOT:g}rem; "
                   f"--hw-{level}-lead: {rem(leading(cap))};")
    return " ".join(out)


def css():
    w = []
    w.append("/* House web layout tokens. Generated by scripts/tokens.py; do not edit by hand. */\n")
    w.append("@import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;0,900;1,300&display=swap');\n")
    w.append(":root {\n  --hw-step: 0.3125rem; /* 5 px */\n  --hw-font: 'Lato', 'Lato Extended', Arial, sans-serif;")
    for k, h in GREYS.items():
        w.append(f"  --hw-k{k}: {h};")
    w.append("  --hw-text: #222222; --hw-text-2: #333333; --hw-text-3: #555555; /* #555 = secondary only */")
    for name, (hh, s, t, _) in DOMAINS.items():
        w.append(f"  --hw-{name}-h: {hh}; --hw-{name}-s: {s}; --hw-{name}-t: {t};")
    for k, (size, lead) in BODY.items():
        w.append(f"  --hw-{k}-size: {rem(size)}; --hw-{k}-lead: {rem(lead)};")
    w.append("}\n")

    # Stepped container: mobile first, then snap up. Queries in em so zoom and text size follow.
    order = [360, 760, 1020, 1200]
    for i, width in enumerate(order):
        rules = [f".hw-page, .hw-page.hw-a {{ {vars_for(width, 'a')} {heading_vars(width)} }}"]
        rules += [f".hw-page.hw-{p} {{ {vars_for(width, p)} }}" for p in "bcd"]
        body = "\n".join(rules)
        if i == 0:
            w.append(body + "\n")
        else:
            w.append(f"@media (min-width: {width / ROOT:g}em) {{\n{body}\n}}\n")

    w.append("""/* Container: fixed at each step, centred. Below 360 px it scrolls rather than break the grid. */
.hw-page { font-family: var(--hw-font); font-size: var(--hw-body-size); line-height: var(--hw-body-lead);
  color: var(--hw-text); background: var(--hw-k0); margin: 0; }
.hw-container { box-sizing: border-box; width: var(--hw-container); margin-inline: auto;
  padding-inline: var(--hw-margin); }

/* 12-column grid, 1:1 ratio rows. Gutters equal both ways. */
.hw-grid { display: grid; grid-template-columns: repeat(12, var(--hw-module));
  column-gap: var(--hw-gutter); row-gap: var(--hw-gutter);
  grid-auto-rows: minmax(var(--hw-row), auto); align-items: start; }
.hw-grid > * { grid-column: 1 / -1; min-width: 0; }
.hw-grid > * { margin: 0; } /* the gutter does the spacing between grid items */
""")
    for n in range(1, 13):
        w.append(f".hw-span-{n} {{ grid-column: span {n} / span {n}; }}")
    for n in range(1, 13):
        w.append(f".hw-start-{n} {{ grid-column-start: {n}; }}")
    for n in range(1, 13):
        w.append(f".hw-rows-{n} {{ grid-row: span {n} / span {n}; "
                 f"min-height: calc({n} * var(--hw-row) + {n - 1} * var(--hw-gutter)); }}")
    w.append("""
/* Spans on smaller containers: md = 760 and up, lg = 1020 and up. Mobile defaults to full width. */""")
    for bp, width in (("md", 760), ("lg", 1020)):
        rules = " ".join(f".hw-{bp}-span-{n} {{ grid-column: span {n} / span {n}; }}" for n in range(1, 13))
        w.append(f"@media (min-width: {width / ROOT:g}em) {{ {rules} }}")
    w.append("""
/* Ratio blocks for media: whole-column spans at a set shape. */
.hw-ratio-1-1 { aspect-ratio: 1 / 1; } .hw-ratio-4-3 { aspect-ratio: 4 / 3; }
.hw-ratio-3-4 { aspect-ratio: 3 / 4; } .hw-ratio-16-9 { aspect-ratio: 16 / 9; }
.hw-ratio-3-2 { aspect-ratio: 3 / 2; }
.hw-media { width: 100%; height: 100%; object-fit: cover; display: block; }

/* Type. Headings: ALL CAPS Lato Black, cap heights in 5 px steps, trimmed to cap/baseline
   so the caps sit on the row line. Space after pads the block to the next row line (snap.js). */
.hw-title, .hw-h1, .hw-h2, .hw-h3, .hw-h4, .hw-h5 { font-weight: 900; text-transform: uppercase;
  margin: 0; text-box: trim-both cap alphabetic; overflow-wrap: break-word; hyphens: manual; }
.hw-title { font-size: var(--hw-title-size); line-height: var(--hw-title-lead); }
.hw-h1 { font-size: var(--hw-h1-size); line-height: var(--hw-h1-lead); }
.hw-h2 { font-size: var(--hw-h2-size); line-height: var(--hw-h2-lead); }
.hw-h3 { font-size: var(--hw-h3-size); line-height: var(--hw-h3-lead); }
.hw-h4 { font-size: var(--hw-h4-size); line-height: var(--hw-h4-lead); }
.hw-h5 { font-size: var(--hw-h5-size); line-height: var(--hw-h5-lead); letter-spacing: 0.1em; }
.hw-subheading { font-weight: 300; text-transform: uppercase; margin: 0; font-size: var(--hw-h2-size);
  line-height: var(--hw-h2-lead); text-box: trim-both cap alphabetic; }
.hw-body, :where(.hw-page) p, :where(.hw-page) li { /* :where keeps this weaker than any class */ font-size: var(--hw-body-size); line-height: var(--hw-body-lead);
  margin: 0 0 var(--hw-body-lead); }
.hw-small { font-size: var(--hw-small-size); line-height: var(--hw-small-lead); }
.hw-condensed { font-size: var(--hw-condensed-size); line-height: var(--hw-condensed-lead); }
.hw-lead { font-weight: 300; font-size: 1.25rem; line-height: var(--hw-body-lead); } /* 20 / 25 */
.hw-caption { font-weight: 400; color: var(--hw-text-2); font-size: var(--hw-small-size); line-height: var(--hw-small-lead); }
.hw-label { font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; font-size: var(--hw-small-size); line-height: var(--hw-small-lead); }
.hw-snap { /* padding-bottom set by snap.js so the block ends on a row line (grid items are snapped anyway) */ }

/* Panels: fills K 10 to K 90, padding = one gutter. Text colour follows the house rules. */
.hw-panel { padding: var(--hw-gutter); box-sizing: border-box; display: flex; flex-direction: column;
  gap: var(--hw-gutter); }
.hw-panel > * { margin: 0; } /* inside a panel, one gutter separates each item */
.hw-k10 { background: var(--hw-k10); color: #000; } .hw-k20 { background: var(--hw-k20); color: #000; }
.hw-k70 { background: var(--hw-k70); color: #fff; } .hw-k80 { background: var(--hw-k80); color: #fff; }
.hw-k90 { background: var(--hw-k90); color: #fff; } .hw-k100 { background: var(--hw-k100); color: #fff; }
/* K 30 to K 60: graphics only, never behind text. White text never Light (300). */
.hw-k70 .hw-lead, .hw-k80 .hw-lead, .hw-k90 .hw-lead, .hw-k100 .hw-lead { font-weight: 400; }
""")
    for name, (_, _, _, on_h) in DOMAINS.items():
        note = "  /* large text and graphics only */" if name in LARGE_ONLY else ""
        w.append(f".hw-{name}-accent {{ background: var(--hw-{name}-h); color: {on_h}; }}{note}")
        w.append(f".hw-{name}-tint {{ background: var(--hw-{name}-t); color: #000; }}")
        fg = "#000" if name == "communication" else "#fff"  # Mustard #CFB500 takes black
        w.append(f".hw-{name}-shade {{ background: var(--hw-{name}-s); color: {fg}; }}")
        w.append(f".hw-{name}-bar {{ border-left: var(--hw-gutter) solid var(--hw-{name}-h); }}")
    w.append("""
/* Tables: header K 90 white bold caps, body condensed, 1 px K 50 rules, optional K 10 banding. */
.hw-table-wrap { overflow-x: auto; } /* tables scroll inside their span on small screens */
.hw-table { border-collapse: collapse; width: 100%; font-size: var(--hw-condensed-size); line-height: var(--hw-condensed-lead); }
.hw-table th { background: var(--hw-k90); color: #fff; font-weight: 700; text-transform: uppercase; text-align: left; padding: var(--hw-step) 0.625rem; }
.hw-table td { border-bottom: 1px solid var(--hw-k50); padding: var(--hw-step) 0.625rem; vertical-align: top; }
.hw-table.hw-banded tr:nth-child(even) td { background: var(--hw-k10); }

/* Grid overlay for checking (toggle .hw-show-grid on .hw-container). */
.hw-show-grid { position: relative; }
.hw-show-grid::before { content: ""; position: absolute; inset: 0 var(--hw-margin); pointer-events: none; z-index: 10;
  background:
    repeating-linear-gradient(to right, rgba(255, 88, 93, .10) 0 var(--hw-module), transparent var(--hw-module) var(--hw-pitch)),
    repeating-linear-gradient(to bottom, transparent 0 var(--hw-row), rgba(50, 98, 149, .25) var(--hw-row) var(--hw-pitch)); }
""")
    return "\n".join(w)


if __name__ == "__main__":
    check()
    cmd = sys.argv[1] if len(sys.argv) > 1 else "table"
    print(css() if cmd == "css" else "", end="") if cmd == "css" else table()
