#!/usr/bin/env python3
"""Generate (and optionally run) an InDesign ExtendScript that builds a document with the full
InDesign Parameters system: grid, swatches, paragraph/character/object/cell/table styles, panels,
parent-page furniture, and (with --sample) a two-page sample layout.

Usage:
  python3 build_indd.py A4P A --out ~/Desktop/Sample.indd [--sample] [--run] [--font Lato] [--domain slug|slug,slug|all]

--run executes it in InDesign via osascript (macOS) and writes a log next to the .indd.
Without --run, the .jsx is written next to the output so it can be run from InDesign's Scripts panel.
Print sizes only (A4P, A4L, A3P, A3L).
"""
import json
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import grid  # noqa: E402


def spec(size, key, font=None, sample=False):
    if size in grid.DIGITAL:
        sys.exit("build_indd.py builds print documents (A4P, A4L, A3P, A3L) only.")
    name, W, H = grid.SIZES[size]
    c, cg, r, rg, L, R, bi, bo, bc, T, B = grid.PRESETS[size][key]
    family, entry = grid.font_entry(font)
    heavy, light = entry["heavy"], entry["light"]
    bold = "Bold" if "Bold" in entry["weights"] else heavy
    pitch_mm = r + rg
    pitch_pt = pitch_mm * grid.MM_TO_PT

    headings = []
    for hname, lines, rows in grid.TYPE_STYLES:
        weight = light if hname == "Subheading" else heavy
        cap = (grid.span(r, rg, rows) - (lines - 1) * rg) / lines
        if cap < grid.MIN_CAP["mm"]:
            continue  # too small / impossible on this preset: style isn't created
        headings.append({"name": hname, "weight": weight,
                         "size": round(cap / entry["weights"][weight]["cap"] * grid.MM_TO_PT, 1),
                         "leading": round((cap + rg) * grid.MM_TO_PT, 1)})

    bodies = {}
    for bname, pt, target, rng, track in grid.BODY_STYLES:
        fit = grid.body_fit(pitch_pt, pt, target, rng)
        bodies[bname] = {"size": pt, "leading": fit[2] if fit else round(pt * 1.35, 1), "tracking": track}

    lp, la, lr = grid.LEAD["print"]
    lead_fit = grid.body_fit(pitch_pt, lp, la, lr, False, grid.LEAD_ROWS)
    qp, qa, qr = grid.PULL_QUOTE["print"]
    q_fit = grid.body_fit(pitch_pt, qp, qa, qr, False, grid.LEAD_ROWS)
    ans = grid.answer_lines(pitch_mm)

    return {
        "size": size, "preset": key, "sizeName": name, "W": W, "H": H,
        "margins": {"top": T, "bottom": B, "left": L, "right": R},
        "col": c, "cg": cg, "row": r, "rg": rg,
        "font": family, "heavy": heavy, "light": light, "bold": bold,
        "capRatios": {w: v["cap"] for w, v in entry["weights"].items()},
        "headings": headings, "bodies": bodies,
        "lead": {"size": lp, "leading": lead_fit[2] if lead_fit else round(lp * 1.3, 1)},
        "pullQuote": {"size": qp, "leading": q_fit[2] if q_fit else round(qp * 1.25, 1)},
        "answer": {"leading": ans[2] if ans else bodies["Body"]["leading"] * 2},
        "indent": grid.INDENT["print"],
        "styleLibrary": [{"folder": f, "name": n, "first": s, "span": k} for f, n, s, k in grid.STYLE_LIBRARY],
        "sample": sample,
        "domains": [],
    }


JSX = r'''
// Generated by InDesign Parameters build_indd.py. Builds grid + styles (+ sample).
#target indesign
var D = __SPEC__;
var OUT = __OUT__;
var LOG = [];
function log(s) { LOG.push(s); }
function mm(v) { return v + "mm"; }
function pt(v) { return v + "pt"; }
function setProps(obj, props, label) {
    for (var k in props) {
        try { obj[k] = props[k]; }
        catch (e) { log("WARN " + label + "." + k + ": " + e.message); }
    }
}

app.scriptPreferences.userInteractionLevel = UserInteractionLevels.NEVER_INTERACT;
app.scriptPreferences.measurementUnit = MeasurementUnits.MILLIMETERS;
var doc = null;
try {

// ---------------------------------------------------------------- document + grid
doc = app.documents.add(false);
setProps(doc.documentPreferences, {
    intent: DocumentIntentOptions.PRINT_INTENT, facingPages: false,
    pageWidth: D.W, pageHeight: D.H, pagesPerDocument: D.sample ? 2 : 1
}, "documentPreferences");
setProps(doc.viewPreferences, {
    horizontalMeasurementUnits: MeasurementUnits.MILLIMETERS,
    verticalMeasurementUnits: MeasurementUnits.MILLIMETERS,
    textSizeMeasurementUnits: MeasurementUnits.POINTS,
    typographicMeasurementUnits: MeasurementUnits.POINTS
}, "viewPreferences");
var M = D.margins;
var marg = { top: M.top, bottom: M.bottom, left: M.left, right: M.right, columnCount: 12, columnGutter: D.cg };
setProps(doc.marginPreferences, marg, "doc.margins");
var parent = doc.masterSpreads[0];
for (var i = 0; i < parent.pages.length; i++) setProps(parent.pages[i].marginPreferences, marg, "parent.margins");
for (var i = 0; i < doc.pages.length; i++) setProps(doc.pages[i].marginPreferences, marg, "page.margins");
try { parent.createGuides(12, 0, mm(D.rg), mm(0), UIColors.CYAN, true, true); }
catch (e) { log("WARN row guides: " + e.message); }

// ---------------------------------------------------------------- swatches
var K = {};
K[0] = doc.swatches.itemByName("Paper");
K[100] = doc.swatches.itemByName("Black");
var greys = [];
for (var k = 10; k <= 90; k += 10) {
    K[k] = doc.colors.add({ name: "K " + k, model: ColorModel.PROCESS, space: ColorSpace.CMYK, colorValue: [0, 0, 0, k] });
    greys.push(K[k]);
}
try { doc.colorGroups.add("Greyscale", greys); } catch (e) { log("WARN colour group: " + e.message); }
// Domain colours (optional, --domain): RGB swatches from the shared house tokens, one group per domain
for (var di = 0; di < D.domains.length; di++) {
    var dm = D.domains[di], dsw = [];
    for (var si = 0; si < dm.swatches.length; si++) {
        var h = dm.swatches[si].hex.replace("#", "");
        var rgb = [parseInt(h.substr(0, 2), 16), parseInt(h.substr(2, 2), 16), parseInt(h.substr(4, 2), 16)];
        try { dsw.push(doc.colors.add({ name: dm.swatches[si].name, model: ColorModel.PROCESS, space: ColorSpace.RGB, colorValue: rgb })); }
        catch (e) { log("WARN domain swatch " + dm.swatches[si].name + ": " + e.message); }
    }
    try { doc.colorGroups.add(dm.name, dsw); } catch (e) { log("WARN domain group: " + e.message); }
}

// ---------------------------------------------------------------- fonts
var FONT = D.font;
function fontOk(style) { try { return app.fonts.itemByName(FONT + "\t" + style).isValid; } catch (e) { return false; } }
var weights = [D.heavy, D.light, D.bold, "Regular", "Italic", "Light Italic"];
for (var i = 0; i < weights.length; i++) log("font " + FONT + " " + weights[i] + ": " + (fontOk(weights[i]) ? "available" : "MISSING"));

// ---------------------------------------------------------------- character styles
var cs = {};
function charStyle(name, props) { var s = doc.characterStyles.add({ name: name }); setProps(s, props, "char " + name); cs[name] = s; return s; }
charStyle("Bold", { appliedFont: FONT, fontStyle: D.bold });
charStyle("Italic", { appliedFont: FONT, fontStyle: "Italic" });
var bodyPt = D.bodies["Body"].size;
charStyle("Key Term", { appliedFont: FONT, fontStyle: D.bold, fillColor: K[100], underline: true,
    underlineWeight: pt(bodyPt + 1), underlineOffset: pt(-Math.round(bodyPt * 3) / 10), underlineColor: K[20], underlineTint: 100 });
charStyle("Link", { underline: true, underlineWeight: pt(0.5), underlineOffset: pt(1.5), fillColor: K[100] });
charStyle("Marks", { appliedFont: FONT, fontStyle: "Regular", pointSize: pt(D.bodies["Body Small"].size) });
charStyle("Step Label", { appliedFont: FONT, fontStyle: D.bold });

// ---------------------------------------------------------------- paragraph styles
var ps = {};
var groups = {};
function group(name) { if (!groups[name]) groups[name] = doc.paragraphStyleGroups.add({ name: name }); return groups[name]; }
function paraStyle(groupName, name, props) {
    var s = group(groupName).paragraphStyles.add({ name: name });
    setProps(s, props, "para " + name);
    ps[name] = s; return s;
}
var basic = doc.paragraphStyles.itemByName("[Basic Paragraph]");
setProps(basic, { appliedFont: FONT, fontStyle: "Regular", hyphenation: false, justification: Justification.LEFT_ALIGN,
    alignToBaseline: false, fillColor: K[100] }, "Basic Paragraph");

// Headings
var hb = paraStyle("Headings", "Heading Base", { basedOn: basic, appliedFont: FONT, fontStyle: D.heavy,
    capitalization: Capitalization.ALL_CAPS, keepWithNext: 1, balanceRaggedLines: true, spaceBefore: 0, spaceAfter: 0 });
for (var i = 0; i < D.headings.length; i++) {
    var h = D.headings[i];
    paraStyle("Headings", h.name, { basedOn: hb, fontStyle: h.weight, pointSize: pt(h.size), leading: pt(h.leading) });
}
// Body
var bodyCommon = { keepLinesTogether: true, keepFirstLines: 2, keepLastLines: 2, spaceBefore: 0, spaceAfter: 0 };
function bodyProps(b, extra) {
    var p = { pointSize: pt(b.size), leading: pt(b.leading), tracking: b.tracking };
    for (var k in bodyCommon) p[k] = bodyCommon[k];
    for (var k in extra) p[k] = extra[k];
    return p;
}
var body = paraStyle("Body", "Body", bodyProps(D.bodies["Body"], { basedOn: basic }));
paraStyle("Body", "Body Condensed", bodyProps(D.bodies["Body Condensed"], { basedOn: body }));
paraStyle("Body", "Body Small", bodyProps(D.bodies["Body Small"], { basedOn: body }));
for (var i = 0; i < D.headings.length; i++) setProps(ps[D.headings[i].name], { nextStyle: body }, "next");
if (ps["Title"] && ps["Subheading"]) { ps["Title"].nextStyle = ps["Subheading"]; ps["Subheading"].nextStyle = body; }

// Lists
var mainList = doc.numberingLists.add({ name: "Main" });
var qList = doc.numberingLists.add({ name: "Questions" });
var stepList = doc.numberingLists.add({ name: "Steps" });
var I = D.indent;
function listProps(extra) {
    var p = { spaceAfter: 0 };
    for (var k in extra) p[k] = extra[k];
    return p;
}
function bullet(style, ch) { style.bulletsAndNumberingListType = ListType.BULLET_LIST; try { style.bulletChar.characterValue = ch; } catch (e) { log("WARN bullet char: " + e.message); } style.bulletsTextAfter = "^t"; }
function numbered(style, list, level, format, expr) {
    style.bulletsAndNumberingListType = ListType.NUMBERED_LIST;
    setProps(style, { appliedNumberingList: list, numberingLevel: level, numberingFormat: format, numberingExpression: expr }, "numbering " + style.name);
}
var bl = paraStyle("Lists", "Bullet", listProps({ basedOn: body, leftIndent: mm(I.bullet), firstLineIndent: mm(-I.bullet) })); bullet(bl, 8226);
var bl2 = paraStyle("Lists", "Bullet Level 2", listProps({ basedOn: bl, leftIndent: mm(2 * I.bullet), firstLineIndent: mm(-I.bullet) })); bullet(bl2, 8211);
var nm = paraStyle("Lists", "Numbered", listProps({ basedOn: body, leftIndent: mm(I.numbered), firstLineIndent: mm(-I.numbered) }));
numbered(nm, mainList, 1, "1, 2, 3, 4...", "^#.^t");
var nm2 = paraStyle("Lists", "Numbered Level 2", listProps({ basedOn: nm, leftIndent: mm(2 * I.numbered), firstLineIndent: mm(-I.numbered) }));
numbered(nm2, mainList, 2, "a, b, c, d...", "^#.^t");
var blc = paraStyle("Lists", "Bullet Condensed", listProps({ basedOn: ps["Body Condensed"], leftIndent: mm(I.bullet), firstLineIndent: mm(-I.bullet) })); bullet(blc, 8226);
var nmc = paraStyle("Lists", "Numbered Condensed", listProps({ basedOn: ps["Body Condensed"], leftIndent: mm(I.numbered), firstLineIndent: mm(-I.numbered) }));
numbered(nmc, mainList, 1, "1, 2, 3, 4...", "^#.^t");
var chk = paraStyle("Lists", "Checklist", listProps({ basedOn: bl, leftIndent: mm(I.numbered), firstLineIndent: mm(-I.numbered) })); bullet(chk, 9633);
var colX1 = D.col + D.cg, colX2 = 2 * (D.col + D.cg);
var step = paraStyle("Lists", "Step", listProps({ basedOn: nm, leftIndent: mm(colX1), firstLineIndent: mm(-colX1) }));
numbered(step, stepList, 1, "1, 2, 3, 4...", "Step ^#^t");
try { step.numberingCharacterStyle = cs["Step Label"]; } catch (e) { log("WARN step char style: " + e.message); }
var def = paraStyle("Lists", "Definition", listProps({ basedOn: body, leftIndent: mm(colX2), firstLineIndent: mm(-colX2) }));
try { var ns = def.nestedStyles.add({ appliedCharacterStyle: cs["Bold"], delimiter: NestedStyleDelimiters.TABS, repetition: 1, inclusive: true }); }
catch (e) { log("WARN definition nested style: " + e.message); }
// Space Between Paragraphs Using Same Style = 0, Space After = one line
var listNames = ["Bullet", "Bullet Level 2", "Numbered", "Numbered Level 2", "Bullet Condensed", "Numbered Condensed", "Checklist", "Step", "Definition"];
for (var i = 0; i < listNames.length; i++) {
    var s = ps[listNames[i]];
    var lead = String(s.leading).replace(/[^0-9.]/g, "");
    try { s.spaceAfter = pt(s.leading); } catch (e) { log("WARN list space after: " + e.message); }
    try { s.sameParaStyleSpacing = 0; } catch (e) { log("WARN " + listNames[i] + " sameParaStyleSpacing: " + e.message); }
}

// Supporting
paraStyle("Supporting", "Lead", { basedOn: body, fontStyle: D.light, pointSize: pt(D.lead.size), leading: pt(D.lead.leading), balanceRaggedLines: true });
paraStyle("Supporting", "Caption", { basedOn: ps["Body Small"], fontStyle: D.light, fillColor: K[80] });
paraStyle("Supporting", "Label", { basedOn: ps["Body Small"], fontStyle: D.heavy, capitalization: Capitalization.ALL_CAPS, tracking: 100, keepWithNext: 1 });
paraStyle("Supporting", "Pull Quote", { basedOn: body, fontStyle: D.light + " Italic", pointSize: pt(D.pullQuote.size), leading: pt(D.pullQuote.leading), balanceRaggedLines: true });
paraStyle("Supporting", "Block Quote", { basedOn: body, fontStyle: "Italic", leftIndent: mm(colX1) });
paraStyle("Supporting", "Footnote", { basedOn: ps["Body Small"], fillColor: K[80] });

// Worksheet
paraStyle("Worksheet", "Learning Intention", { basedOn: ps["Label"] });
paraStyle("Worksheet", "Success Criteria", { basedOn: ps["Label"] });
var q = paraStyle("Worksheet", "Question", { basedOn: nm, fontStyle: D.bold, keepWithNext: 1 });
numbered(q, qList, 1, "1, 2, 3, 4...", "^#.^t");
var qp = paraStyle("Worksheet", "Question Part", { basedOn: nm2, fontStyle: "Regular" });
numbered(qp, qList, 2, "a, b, c, d...", "(^#)^t");
paraStyle("Worksheet", "Instruction", { basedOn: body, fontStyle: "Italic" });
var ansStyle = paraStyle("Worksheet", "Answer Line", { basedOn: body, leading: pt(D.answer.leading), keepLinesTogether: false,
    ruleBelow: true, ruleBelowLineWeight: pt(0.5), ruleBelowColor: K[100], ruleBelowTint: 100, ruleBelowOffset: 0,
    ruleBelowWidth: RuleWidth.COLUMN_WIDTH });
q.nextStyle = ansStyle;

// Page furniture
paraStyle("Page", "Page Number", { basedOn: ps["Body Small"], fontStyle: D.bold, justification: Justification.RIGHT_ALIGN });
paraStyle("Page", "Running Footer", { basedOn: ps["Body Small"], fillColor: K[80] });

// Tables
paraStyle("Tables", "Table Header", { basedOn: ps["Body Condensed"], fontStyle: D.bold, capitalization: Capitalization.ALL_CAPS,
    tracking: 25, fillColor: K[0] });
paraStyle("Tables", "Table Body", { basedOn: ps["Body Condensed"] });

// Reversed variants (white, for K 70-100 panels). Never Light/Thin styles.
var reversible = ["Title", "Heading 1", "Heading 2", "Heading 3", "Heading 4", "Heading 5", "Body", "Body Condensed", "Bullet", "Numbered", "Label"];
for (var i = 0; i < reversible.length; i++) {
    var src = ps[reversible[i]];
    if (!src || !src.isValid) continue;
    paraStyle("Reversed", reversible[i] + " – Reversed", { basedOn: src, fillColor: K[0] });
}

// ---------------------------------------------------------------- object styles
var os = {};
function tfPrefs(o, prefs, label) { setProps(o.textFramePreferences, prefs, label + ".textFramePreferences"); }
// Child object styles don't pick up these settings from Based On when made by script,
// so every style gets them explicitly.
function gridSettings(st, label) {
    setProps(st, { enableTextFrameGeneralOptions: true, enableTextFrameBaselineOptions: true,
        enableTextFrameAutoSizingOptions: true, enableFill: true, enableStroke: true,
        fillColor: doc.swatches.itemByName("None"), strokeColor: doc.swatches.itemByName("None"), strokeWeight: 0 }, label);
    tfPrefs(st, { insetSpacing: [0, 0, 0, 0], textColumnCount: 1, firstBaselineOffset: FirstBaseline.CAP_HEIGHT,
        autoSizingType: AutoSizingTypeEnum.HEIGHT_ONLY, autoSizingReferencePoint: AutoSizingReferenceEnum.TOP_CENTER_POINT,
        verticalJustification: VerticalJustification.TOP_ALIGN }, label);
}
var base = doc.objectStyles.add({ name: "Text – Grid" });
gridSettings(base, "Text – Grid");
os["Text – Grid"] = base;

var ogroups = {};
function objGroup(path) {
    if (!path) return null;
    if (ogroups[path]) return ogroups[path];
    var parts = path.split(" › ");
    var parentG = null, acc = "";
    for (var i = 0; i < parts.length; i++) {
        acc = acc ? acc + " › " + parts[i] : parts[i];
        if (!ogroups[acc]) ogroups[acc] = (parentG ? parentG : doc).objectStyleGroups.add({ name: parts[i] });
        parentG = ogroups[acc];
    }
    return ogroups[path];
}
var sizePosOk = true;
function positionStyle(entry) {
    var g = objGroup(entry.folder);
    var s = (g ? g : doc).objectStyles.add({ name: entry.name, basedOn: base });
    gridSettings(s, entry.name);
    var width = entry.span * D.col + (entry.span - 1) * D.cg;
    var x = (entry.first - 1) * (D.col + D.cg);
    try {
        s.enableTransformAttributes = true;
        var t = s.transformAttributeOptions;
        t.transformAttrWidth = width;
        t.transformAttrX = x;
        t.transformAttrLeftReference = TransformPositionReference.PAGE_MARGIN_REFERENCE;
        t.transformAttrRefAnchorPoint = AnchorPoint.TOP_LEFT_ANCHOR;
    } catch (e) { if (sizePosOk) log("WARN object style size/position: " + e.message); sizePosOk = false; }
    os[entry.name + "|" + entry.folder] = s;
    if (!os[entry.name]) os[entry.name] = s;
    return s;
}
for (var i = 0; i < D.styleLibrary.length; i++) positionStyle(D.styleLibrary[i]);

// Answer lines: first baseline = leading, so the first rule sits one full line below the frame top
var wsG = doc.objectStyleGroups.add({ name: "Worksheet" });
var ansObj = wsG.objectStyles.add({ name: "Answer Lines", basedOn: base });
gridSettings(ansObj, "Answer Lines");
tfPrefs(ansObj, { firstBaselineOffset: FirstBaseline.LEADING_OFFSET }, "Answer Lines");
os["Answer Lines"] = ansObj;

// Panels
var panelsG = doc.objectStyleGroups.add({ name: "Panels" });
function panelStyle(name, k) {
    var s = panelsG.objectStyles.add({ name: name, basedOn: base });
    gridSettings(s, name);
    setProps(s, { fillColor: K[k] }, name);
    tfPrefs(s, { insetSpacing: [D.rg, D.cg, D.rg, D.cg], autoSizingType: AutoSizingTypeEnum.OFF }, name);
    os[name] = s; return s;
}
panelStyle("Accent – K 100", 100);
panelStyle("Panel – K 90", 90); panelStyle("Panel – K 80", 80); panelStyle("Panel – K 70", 70);
panelStyle("Panel – K 20", 20); panelStyle("Panel – K 10", 10);

// ---------------------------------------------------------------- cell + table styles
var cellH = doc.cellStyles.add({ name: "Table Header" });
setProps(cellH, { fillColor: K[90], topInset: D.rg, bottomInset: D.rg, leftInset: D.cg, rightInset: D.cg,
    appliedParagraphStyle: ps["Table Header"], verticalJustification: VerticalJustification.TOP_ALIGN,
    firstBaselineOffset: FirstBaseline.CAP_HEIGHT }, "cell Table Header");
var cellB = doc.cellStyles.add({ name: "Table Body" });
setProps(cellB, { fillColor: doc.swatches.itemByName("None"), topInset: D.rg, bottomInset: D.rg, leftInset: D.cg, rightInset: D.cg,
    appliedParagraphStyle: ps["Table Body"], bottomEdgeStrokeWeight: pt(0.5), bottomEdgeStrokeColor: K[50],
    topEdgeStrokeWeight: 0, leftEdgeStrokeWeight: 0, rightEdgeStrokeWeight: 0,
    firstBaselineOffset: FirstBaseline.CAP_HEIGHT }, "cell Table Body");
var cellBand = doc.cellStyles.add({ name: "Table Body Banded", basedOn: cellB });
setProps(cellBand, { fillColor: K[10] }, "cell Banded");
var tstyle = doc.tableStyles.add({ name: "Table" });
setProps(tstyle, { headerRegionCellStyle: cellH, bodyRegionCellStyle: cellB,
    topBorderStrokeWeight: 0, bottomBorderStrokeWeight: 0, leftBorderStrokeWeight: 0, rightBorderStrokeWeight: 0 }, "table style");

// ---------------------------------------------------------------- parent page furniture
var pp = parent.pages[0];
function colX(c) { return M.left + (c - 1) * (D.col + D.cg); }
function spanW(n) { return n * D.col + (n - 1) * D.cg; }
function rowY(r) { return M.top + (r - 1) * (D.row + D.rg); }
var fy1 = D.H - M.bottom, fy2 = D.H;
var foot = pp.textFrames.add({ geometricBounds: [fy1, colX(1), fy2, colX(1) + spanW(8)] });
foot.contents = "InDesign Parameters · " + D.sizeName + " · Preset " + D.preset;
foot.paragraphs[0].appliedParagraphStyle = ps["Running Footer"];
var num = pp.textFrames.add({ geometricBounds: [fy1, colX(9), fy2, colX(9) + spanW(4)] });
num.contents = SpecialCharacters.AUTO_PAGE_NUMBER;
num.paragraphs[0].appliedParagraphStyle = ps["Page Number"];
var furniture = [foot, num];
for (var i = 0; i < furniture.length; i++) {
    setProps(furniture[i].textFramePreferences, { insetSpacing: [0, 0, 0, 0], firstBaselineOffset: FirstBaseline.CAP_HEIGHT,
        verticalJustification: VerticalJustification.CENTER_ALIGN, autoSizingType: AutoSizingTypeEnum.OFF }, "furniture");
}

// ---------------------------------------------------------------- measure the font's real cap ratios
try {
    var mp = doc.pages[0];
    var toMeasure = [D.heavy, D.light, D.bold, "Regular"];
    for (var i = 0; i < toMeasure.length; i++) {
        if (!fontOk(toMeasure[i])) continue;
        var tf = mp.textFrames.add({ geometricBounds: [0, 0, 60, 60] });
        tf.contents = "H";
        setProps(tf.paragraphs[0], { appliedFont: FONT, fontStyle: toMeasure[i], pointSize: pt(100) }, "measure");
        var outl = tf.createOutlines(true)[0];
        var gb = outl.geometricBounds;
        var ratio = (gb[2] - gb[0]) / (100 * 25.4 / 72);
        log("capRatio " + toMeasure[i] + " measured " + ratio.toFixed(4) + " (skill uses " + D.capRatios[toMeasure[i]] + ")");
        outl.remove();
    }
} catch (e) { log("WARN cap measurement: " + e.message); }

// ---------------------------------------------------------------- sample layout
var placeChecked = false;
function place(page, c1, span, r1, paras, objStyleName, fixedRows) {
    var top = rowY(r1), left = colX(c1);
    var bottom = fixedRows ? top + fixedRows * D.row + (fixedRows - 1) * D.rg : top + 10;
    var tf = page.textFrames.add({ geometricBounds: [top, left, bottom, left + spanW(span)] });
    var st = os[objStyleName] || base;
    if (!placeChecked) tf.geometricBounds = [top, 0, bottom, 30];   // deliberately off-grid to test the style
    try { tf.applyObjectStyle(st, true); } catch (e) { log("WARN apply object style " + objStyleName + ": " + e.message); }
    var text = [];
    for (var i = 0; i < paras.length; i++) text.push(paras[i][1] === "" ? " " : paras[i][1]);
    tf.contents = text.join("\r");
    for (var i = 0; i < paras.length; i++) {
        try { tf.paragraphs[i].appliedParagraphStyle = ps[paras[i][0]]; } catch (e) { log("WARN style " + paras[i][0] + ": " + e.message); }
    }
    // {RIT} marks a right indent tab (pushes marks to the frame's right edge)
    if (tf.contents.indexOf("{RIT}") >= 0) {
        app.findTextPreferences = NothingEnum.NOTHING; app.changeTextPreferences = NothingEnum.NOTHING;
        app.findTextPreferences.findWhat = "{RIT}"; app.changeTextPreferences.changeTo = "^y";
        tf.changeText();
        app.findTextPreferences = NothingEnum.NOTHING; app.changeTextPreferences = NothingEnum.NOTHING;
    }
    // check whether the object style alone put the frame in the right place
    if (!placeChecked && st !== base && objStyleName.indexOf("Panel") < 0 && objStyleName.indexOf("Accent") < 0) {
        var g0 = tf.geometricBounds;
        log("object style check (" + objStyleName + "): x " + (Math.round(g0[1] * 100) / 100) + " expected " + left +
            ", width " + (Math.round((g0[3] - g0[1]) * 100) / 100) + " expected " + spanW(span));
        placeChecked = true;
    }
    // re-assert exact geometry (object style size/position may not be supported)
    var gb = tf.geometricBounds;
    tf.geometricBounds = [top, left, fixedRows ? bottom : gb[2], left + spanW(span)];
    // final: no stroke on text frames (panels included); fills come from the object style
    // Only set the colour: setting strokeWeight on an unstroked frame turns on a 1 pt black stroke.
    try { tf.strokeColor = doc.swatches.itemByName("None"); } catch (e) { log("WARN stroke: " + e.message); }
    if (objStyleName === "Answer Lines") {
        tf.textFramePreferences.firstBaselineOffset = FirstBaseline.LEADING_OFFSET;
    }
    if (tf.overflows) log("WARN overset text in frame at col " + c1 + " row " + r1);
    return tf;
}
function applyChar(tf, word, styleName) {
    app.findTextPreferences = NothingEnum.NOTHING; app.changeTextPreferences = NothingEnum.NOTHING;
    app.findTextPreferences.findWhat = word;
    var hits = tf.findText();
    for (var i = 0; i < hits.length; i++) hits[i].appliedCharacterStyle = cs[styleName];
    app.findTextPreferences = NothingEnum.NOTHING;
}
function rect(page, c1, span, r1, rows, k) {
    var top = rowY(r1), left = colX(c1);
    var rc = page.rectangles.add({ geometricBounds: [top, left, top + rows * D.row + (rows - 1) * D.rg, left + spanW(span)] });
    rc.fillColor = K[k]; rc.strokeColor = doc.swatches.itemByName("None");
    return rc;
}

if (D.sample) {
    var p1 = doc.pages[0], p2 = doc.pages[1];
    // Page 1: handout
    place(p1, 1, 12, 1, [["Title", "Contrast"]], "Full Width");
    place(p1, 1, 8, 2, [["Subheading", "Creating emphasis and focus"]], "2/3 Page – Left");
    place(p1, 10, 3, 2, [["Label – Reversed", "Unit 2 · Week 3"]], "Accent – K 100", 1);
    place(p1, 1, 8, 3, [["Lead", "Contrast is the difference between elements on a page. Designers use it to show what matters most and where to look first."]], "2/3 Page – Left");
    place(p1, 9, 4, 3, [["Label", "In this handout"], ["Bullet Condensed", "What contrast is"], ["Bullet Condensed", "Five ways to create it"], ["Bullet Condensed", "Activity: apply it"]], "Panel – K 10", 2);
    place(p1, 1, 6, 5, [["Heading 2", "What is contrast?"]], "1/2 Page – Left");
    place(p1, 7, 6, 5, [["Heading 2", "Five ways to create it"]], "1/2 Page – Right");
    var b1 = place(p1, 1, 6, 6, [
        ["Body", "Contrast happens when two elements are clearly different. The bigger the difference, the more the eye is drawn to it."],
        ["Body", "Used well, contrast creates a visual hierarchy: the reader sees the most important element first, then the next, and so on down the page."]], "1/2 Page – Left");
    applyChar(b1, "visual hierarchy", "Key Term");
    place(p1, 7, 6, 6, [["Numbered", "Size: make key elements larger."], ["Numbered", "Weight: use bold against light."],
        ["Numbered", "Tone: set dark against light."], ["Numbered", "Space: surround elements with white space."],
        ["Numbered", "Position: place key content where the eye lands first."]], "1/2 Page – Right");
    rect(p1, 1, 6, 8, 2, 30);
    place(p1, 1, 6, 10, [["Caption", "Image placeholder (K 30 graphic fill). Captions sit on the row line below the image."]], "1/2 Page – Left");
    place(p1, 7, 6, 8, [["Pull Quote", "Good contrast makes the important things impossible to miss."]], "1/2 Page – Right");
    place(p1, 7, 6, 10, [["Heading 3 – Reversed", "Remember"], ["Body – Reversed", "Contrast must also be accessible. Text needs at least 7:1 contrast with its background."]], "Panel – K 90", 2);
    place(p1, 1, 6, 11, [["Label", "Key terms"], ["Definition", "Contrast\tA clear difference."], ["Definition", "Hierarchy\tThe order we read in."]], "1/2 Page – Left");
    place(p1, 1, 6, 12, [["Footnote", "Sample text written for this template."]], "1/2 Page – Left");

    // Page 2: worksheet. An answer area of n rows holds (lines per row x n) - 1 lines, so its last
    // line sits inside the area and the next question starts clear of it.
    place(p2, 1, 12, 1, [["Heading 1", "Apply contrast"]], "Full Width");
    place(p2, 1, 6, 2, [["Learning Intention", "Learning intention"], ["Body", "I am learning to use contrast to create hierarchy."]], "Panel – K 10", 1);
    place(p2, 7, 6, 2, [["Success Criteria", "Success criteria"], ["Checklist", "I can name three types of contrast."], ["Checklist", "I can explain what stands out and why."]], "Panel – K 10", 2);
    place(p2, 1, 12, 4, [["Instruction", "Look at the poster your teacher shows you, then answer the questions below."]], "Full Width");
    place(p2, 1, 12, 5, [["Question", "Which element on the poster stands out first? Explain why.{RIT}(2 marks)"]], "Full Width");
    place(p2, 1, 12, 6, [["Answer Line", ""], ["Answer Line", ""], ["Answer Line", ""]], "Answer Lines");
    place(p2, 1, 12, 8, [["Question", "Name two ways the designer has used contrast.{RIT}(2 marks)"]], "Full Width");
    place(p2, 1, 12, 9, [["Answer Line", ""], ["Answer Line", ""], ["Answer Line", ""]], "Answer Lines");
    // table
    var tfT = place(p2, 1, 12, 11, [["Table Body", "{TABLE}"]], "Full Width");
    tfT.contents = "";
    var tbl = tfT.insertionPoints[0].tables.add({ headerRowCount: 1, bodyRowCount: 2, columnCount: 3 });
    var widths = [spanW(4) + D.cg, spanW(4) + D.cg, spanW(4)];
    for (var i = 0; i < 3; i++) tbl.columns[i].width = widths[i];
    tbl.appliedTableStyle = tstyle;
    var cellsText = [["Type", "Example", "Effect"], ["Size", "Large heading", "Seen first"], ["Tone", "Dark panel", "Groups content"]];
    for (var rI = 0; rI < 3; rI++) for (var cI = 0; cI < 3; cI++) tbl.rows[rI].cells[cI].contents = cellsText[rI][cI];
    try { tbl.rows[0].cells.everyItem().appliedCellStyle = cellH; tbl.rows[0].cells.everyItem().texts[0].appliedParagraphStyle = ps["Table Header"]; } catch (e) { log("WARN header cells: " + e.message); }
    for (var rI = 1; rI < 3; rI++) {
        try { tbl.rows[rI].cells.everyItem().appliedCellStyle = (rI % 2 == 0) ? cellBand : cellB; tbl.rows[rI].cells.everyItem().texts[0].appliedParagraphStyle = ps["Table Body"]; } catch (e) { log("WARN body cells: " + e.message); }
    }
}

// ---------------------------------------------------------------- save + export previews
var outFile = new File(OUT);
doc.save(outFile);
try {
    app.pngExportPreferences.properties = { exportResolution: 110, pngExportRange: PNGExportRangeEnum.EXPORT_ALL, pngQuality: PNGQualityEnum.HIGH, transparentBackground: false };
    doc.exportFile(ExportFormat.PNG_FORMAT, new File(OUT.replace(/\.indd$/, ".png")), false);
} catch (e) { log("WARN png export: " + e.message); }
try { doc.exportFile(ExportFormat.PDF_TYPE, new File(OUT.replace(/\.indd$/, ".pdf")), false); } catch (e) { log("WARN pdf export: " + e.message); }
doc.close(SaveOptions.NO);
log("OK saved " + OUT);
} catch (e) {
    log("ERROR line " + e.line + ": " + e.message);
    try { if (doc && doc.isValid) doc.close(SaveOptions.NO); } catch (e2) {}
}
var lf = new File(OUT.replace(/\.indd$/, "-build-log.txt"));
lf.encoding = "UTF-8"; lf.open("w"); lf.write(LOG.join("\n")); lf.close();
app.scriptPreferences.measurementUnit = AutoEnum.AUTO_VALUE;
app.scriptPreferences.userInteractionLevel = UserInteractionLevels.INTERACT_WITH_ALL;
"done";
'''


def main(argv):
    if len(argv) < 2:
        sys.exit(__doc__)
    size, key = argv[0].upper(), argv[1].upper()
    opt = lambda f: argv[argv.index(f) + 1] if f in argv else None
    out = os.path.abspath(os.path.expanduser(opt("--out") or f"InDesign-Parameters-{size}-{key}.indd"))
    data = spec(size, key, opt("--font"), "--sample" in argv)
    dom = opt("--domain")
    if dom:
        slugs = list(grid.DOMAINS) if dom == "all" else dom.split(",")
        for slug in slugs:
            if slug not in grid.DOMAINS:
                sys.exit(f"Unknown domain '{slug}'. Options: {', '.join(grid.DOMAINS)} or all")
            name, *sw = grid.DOMAINS[slug]
            data["domains"].append({"name": name, "swatches": [{"name": n, "hex": h} for n, h in sw]})
    jsx = JSX.replace("__SPEC__", json.dumps(data)).replace("__OUT__", json.dumps(out))
    jsx_path = out[:-5] + ".jsx"
    with open(jsx_path, "w", encoding="utf-8-sig") as f:
        f.write(jsx)
    print(f"Wrote {jsx_path}")
    if "--run" in argv:
        script = (f'tell application id "com.adobe.InDesign" to do script (POSIX file "{jsx_path}") '
                  f'language javascript')
        res = subprocess.run(["osascript", "-e", script], capture_output=True, text=True, timeout=600)
        print(res.stdout.strip() or res.stderr.strip())
        log = out[:-5] + "-build-log.txt"
        if os.path.exists(log):
            print(open(log, encoding="utf-8").read())


if __name__ == "__main__":
    main(sys.argv[1:])
